import { useEffect, useState } from 'react';
import { taskApi, type TaskInput } from '../../services/taskApi';
import { SchedulePicker } from '../../components/SchedulePicker';
import { useWorkspaceStore } from '../../stores/workspaceStore';
import type { Task } from '../../types/domain';

const empty: TaskInput = { title: '', description: '', estimatedDurationMinutes: 60, remainingDurationMinutes: 60, priority: 'MEDIUM', status: 'TODO', minimumSessionMinutes: 30, maximumSessionMinutes: 120 };
export function TasksPage() {
  const { activeScheduleId } = useWorkspaceStore();
  const [items, setItems] = useState<Task[]>([]); const [form, setForm] = useState<TaskInput>(empty); const [error, setError] = useState('');
  const load = () => activeScheduleId && taskApi.list(activeScheduleId).then((page) => setItems(page.content)).catch(() => setError('Could not load tasks.'));
  useEffect(() => { void load(); }, [activeScheduleId]);
  const update = (key: keyof TaskInput, value: string | number) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!activeScheduleId || !form.title.trim()) return; try { const created = await taskApi.create(activeScheduleId, form); setItems((old) => [created, ...old]); setForm(empty); } catch { setError('Could not create task. Check duration values.'); } };
  const remove = async (id: string) => { try { await taskApi.remove(id); setItems((old) => old.filter((item) => item.id !== id)); } catch { setError('Could not delete task.'); } };
  const complete = async (task: Task) => { try { const updated = await taskApi.update(task.id, { title: task.title, description: task.description ?? '', estimatedDurationMinutes: task.estimatedDurationMinutes, remainingDurationMinutes: 0, priority: task.priority, deadline: task.deadline ?? undefined, status: 'COMPLETED', categoryId: task.categoryId ?? undefined, minimumSessionMinutes: task.minimumSessionMinutes, maximumSessionMinutes: task.maximumSessionMinutes }); setItems((old) => old.map((item) => item.id === task.id ? updated : item)); } catch { setError('Could not complete task.'); } };
  return <section className="workspace-page"><div className="section-heading"><div><p className="eyebrow">Work to plan</p><h2>Tasks</h2></div><SchedulePicker /></div>{error && <div className="form-error">{error}</div>} {!activeScheduleId ? <div className="panel empty-state"><strong>Create a schedule first</strong><span>Tasks belong to a planning workspace.</span></div> : <div className="two-column"><form className="panel form-panel" onSubmit={submit}><h3>Add a task</h3><label className="field"><span>Title</span><input value={form.title} onChange={(e) => update('title', e.target.value)} required /></label><label className="field"><span>Estimated minutes</span><input type="number" min="1" value={form.estimatedDurationMinutes} onChange={(e) => update('estimatedDurationMinutes', Number(e.target.value))} /></label><label className="field"><span>Remaining minutes</span><input type="number" min="0" value={form.remainingDurationMinutes} onChange={(e) => update('remainingDurationMinutes', Number(e.target.value))} /></label><label className="field"><span>Deadline</span><input type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={form.deadline?.slice(0, 16) ?? ''} onChange={(e) => update('deadline', e.target.value ? new Date(e.target.value).toISOString() : '')} /></label><label className="field"><span>Priority</span><select value={form.priority} onChange={(e) => update('priority', e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><button className="primary-button">Add task</button></form><div className="panel"><div className="panel-heading"><h3>Task list</h3><span className="muted">{items.length} shown</span></div>{items.length === 0 ? <div className="empty-state compact"><span>No tasks yet.</span></div> : <div className="resource-list">{items.map((task) => <div className="resource-row" key={task.id} style={{ opacity: task.status === 'COMPLETED' ? 0.65 : 1 }}><div><strong style={{ textDecoration: task.status === 'COMPLETED' ? 'line-through' : 'none' }}>{task.status === 'COMPLETED' ? `✓ ${task.title}` : task.title}</strong><span>{task.priority} · {task.remainingDurationMinutes} min · {task.status}{task.deadline ? ` · due ${new Date(task.deadline).toLocaleDateString()}` : ''}</span></div><div>{task.status !== 'COMPLETED' && <button className="icon-button" onClick={() => void complete(task)}>Complete</button>}<button className="icon-button danger" onClick={() => void remove(task.id)}>Delete</button></div></div>)}</div>}</div></div>}</section>;
}
